package org.openbase.bco.device.hass.manager.dto

enum class HassDeviceClass(
    val id: String,
) {
    APPARENT_POWER("apparent_power"),
    AQI("aqi"),
    AREA("area"),
    ATMOSPHERIC_PRESSURE("atmospheric_pressure"),
    AWNING("awning"),
    BATTERY("battery"),
    BUTTON("button"),
    BATTERY_CHARGING("battery_charging"),
    BLOOD_GLUCOSE_CONCENTRATION("blood_glucose_concentration"),
    BLIND("blind"),
    CARBON_DIOXIDE("carbon_dioxide"),
    CARBON_MONOXIDE("carbon_monoxide"),
    COLD("cold"),
    CONNECTIVITY("connectivity"),
    CURRENT("current"),
    CURTAIN("curtain"),
    DAMPER("damper"),
    DATA_RATE("data_rate"),
    DATA_SIZE("data_size"),
    DATE("date"),
    DISTANCE("distance"),
    DOOR("door"),
    DURATION("duration"),
    ENERGY("energy"),
    ENERGY_DISTANCE("energy_distance"),
    ENERGY_STORAGE("energy_storage"),
    ENUM("enum"),
    FREQUENCY("frequency"),
    GARAGE("garage"),
    GARAGE_DOOR("garage_door"),
    GAS("gas"),
    GATE("gate"),
    HEAT("heat"),
    HUMIDITY("humidity"),
    IDENTITY("identity"),
    ILLUMINANCE("illuminance"),
    IRRADIANCE("irradiance"),
    LIGHT("light"),
    LOCK("lock"),
    MOISTURE("moisture"),
    MONETARY("monetary"),
    MOTION("motion"),
}