package org.openbase.bco.device.hass.type

enum class HassServiceType(
    val id: String,
) {
    TURN_OFF("turn_off"),
    TURN_ON("turn_on"),
    TOGGLE("toggle"),
    RELOAD("reload"),
    UPDATE_ENTITY("update_entity"),
    SET_VALUE("set_value"),
    INCREMENT("increment"),
    DECREMENT("decrement"),
    SET_COVER_POSITION("set_cover_position"),
    OPEN_COVER("open_cover"),
    CLOSE_COVER("close_cover"),
    STOP_COVER("stop_cover"),
    SET_FAN_SPEED("set_fan_speed"),
    SET_HVAC_MODE("set_hvac_mode"),
    SET_TEMPERATURE("set_temperature"),
    SET_HUMIDITY("set_humidity"),
    SET_COLOR("set_color"),
    SET_BRIGHTNESS("set_brightness"),
    PLAY_MEDIA("play_media"),
    STOP_MEDIA("stop_media"),
    PAUSE_MEDIA("pause_media"),
    NEXT_TRACK("media_next_track"),
    PREVIOUS_TRACK("media_previous_track"),
    SEEK_MEDIA("media_seek"),
    SHUFFLE_SET("shuffle_set"),
    VOLUME_SET("volume_set"),
    VOLUME_UP("volume_up"),
    VOLUME_DOWN("volume_down"),
    MUTE_VOLUME("mute_volume"),
    SET_SCENE("set_scene"),
    RUN_SCRIPT("run_script"),
    TURN_ON_SCRIPT("turn_on_script"),
    TURN_OFF_SCRIPT("turn_off_script"),
    TRIGGER_AUTOMATION("trigger_automation"),
    START_TIMER("start"),
    PAUSE_TIMER("pause"),
    CANCEL_TIMER("cancel"),
    FINISH_TIMER("finish"),
    RESET_TIMER("reset"),
    LOCK("lock"),
    UNLOCK("unlock"),
    OPEN_LOCK("open"),
    SET_ALARM_MODE("set_alarm_mode"),
    ARM_HOME("arm_home"),
    ARM_AWAY("arm_away"),
    ARM_NIGHT("arm_night"),
    DISARM("disarm"),
    TRIGGER_ALARM("trigger"),
    START_VACUUM("start"),
    STOP_VACUUM("stop"),
    RETURN_TO_BASE("return_to_base"),
    CLEAN_SPOT("clean_spot"),
    LOCATE_VACUUM("locate"),
    SET_VACUUM_FAN_SPEED("set_fan_speed"),
    UNKNOWN("unknown");

    companion object {
        fun fromId(id: String): HassServiceType? = HassServiceType.entries.find { it.id == id }
    }
}
